baseurl: "" # the subpath of your site, e.g. /blog
url: "https://csc491.dcsil.ca" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-readme-index
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-relative-links

compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

readme_index:
  enabled: true
  remove_originals: true

sass:
  sass_dir: assets/scss
  style: compressed

source: ./
include:
  - README.md

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - SECURITY.md
