name: rubric

on:
  push:
    branches: [main, master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.18.0
        with:
          # Engine and version to use, see the syntax in the README. Reads from .ruby-version if unset.
          ruby-version: 2.6.5
      - name: Run rubric
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bin/rubrics
      - name: Commit files
        run: |
          if [ ! -z "$(git status --porcelain)" ]; then 
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add --all .
            git commit -m "Update rubrics"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@fe38f0a751bf9149f0270cc1fe20bf9156854365
        env:
          GITHUB_ACTOR: "jules2689" 
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          
